---
title: "hw5"
author: "Matthew Spotnitz"
date: "11/14/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(rvest)
library(stringr)
```
##Problem 1
```{r}
homicide_df = read.csv("homicide-data.csv")
head(homicide_df)
tail(homicide_df)
str(homicide_df)
view(homicide_df)
```
This data set consists of 52179 observations and 12 variables.  Of those variables, all are characters except for "lat" and "lon", which are integers.

```{r}
homicide_df = janitor::clean_names(homicide_df)
homicide_df = homicide_df %>% mutate (
  city_state = str_c(city, state),
  resolution = case_when(
    disposition == "Closed without arrest" ~ "unsolved",
    disposition == "Open/No arrest" ~ "unsolved",
    disposition == "Closed by arrest" ~ "solved" 
  )) %>% 
  relocate(city_state) %>% 
  filter(city_state != "TulsaAL")
```
Now I will focus on Baltimore, MD
```{r}
baltimore_df = homicide_df %>% filter(city_state == "BaltimoreMD")

baltimore_summary = baltimore_df %>% summarize(
  unsolved = sum(resolution == "unsolved"), n = n()
) 

baltimore_test = prop.test(
  x = baltimore_summary %>% pull(unsolved),
  n = baltimore_summary %>% pull(n)
)

baltimore_test %>% broom::tidy()

```
Now I will iterate this function.

```{r}
prop_test_function = function(city_df) {
  city_summary = 
    city_df %>% 
    summarize(
      unsolved = sum(resolution == "unsolved"), n = n()
) 

city_test = prop.test(
  x = city_summary %>% pull(unsolved),
  n = city_summary %>% pull(n))
  
  return(city_test)

 
}

prop_test_function(baltimore_df)

homicide_df %>%
  filter(city_state == "AlbuquerqueNM") %>% 
  prop_test_function()
```
Now, I will iterate across all cities.
```{r}
results_df =
  homicide_df %>% 
  nest(data = uid:resolution) %>% 
  mutate(
    test_results = map(data, prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest  (tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))
```
Now I will make a plot showing estimates and confidence intervals
```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin=conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust= 0.5, hjust = 1))
```
##Problem 2
```{r}
regexp = "[[:digit:]]+"
df_files = tibble(
  files = list.files("./data/zip_data/", pattern="*.csv", full.names=TRUE),
)
head(df_files)
for (i in df_files) {
  read_files = purrr::map(i, read.csv)
  df_files = df_files %>% mutate(tidy_results = purrr::map(read_files, broom::tidy)) #tidy of the data
  df_files = df_files %>% mutate (arm = str_detect(i, "con")) %>% mutate(arm = as.integer(arm)) %>% mutate (arm = factor(arm, labels = c('experimental', 'control') )) #extracting control and experimental groups from the names
df_files = df_files %>% mutate (subject_id = (str_extract(i, regexp))) # extracting subject ids
}

#for (i in files) {
#  print(i)
#  print (str_detect(i, "con"))

#}
  
  
 # if (str_detect(i, "con")) {
 #print("control")
  #}
  #if (str_detect(i, "exp")) {
 #print("experimental")
#  }
#}
view(df_files)
```
##Problem 3
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

fill_in_missing = function(vector){
  if (is.numeric){
    
    .....
    
  }
  if (is.character){
    
    ...
  }
}
```